In [2]:
import numpy as np


---
rank of a matrix
---


In [36]:
m = 4
n = 6

A =  np.random.randn(4,6)
ra = np.linalg.matrix_rank(A)
print("Rank of the matrix A is " + str(ra))

# set last two columns equal to each other
B = np.random.randn(4,6)
B[:,-1] = B[:,-2]

print(B)
ra = np.linalg.matrix_rank(B)
print("Rank of the matrix B is " + str(ra))

# set last two rows equal to each other
C = np.random.randn(4,6)
C[-1,:] = C[-2,:]

print(C)
ra = np.linalg.matrix_rank(C)
print("Rank of the matrix C is " + str(ra))


#adding noise

A = np.round(10*np.random.randn(m,m))
A[:,0] = A[:,1]
print(A)

noiseamp = .0000000000001
B = A + noiseamp*np.random.randn(m,m)
print(B)

raa = np.linalg.matrix_rank(A)
rab = np.linalg.matrix_rank(B)
print("Rank of the matrix A is " + str(raa))
print("Rank of the matrix B is " + str(rab))

Rank of the matrix A is 4
[[-0.13954194  1.50020992  0.63840774  0.48743592  0.03358181  0.03358181]
 [-0.02553775 -0.17559445  0.78340912  0.33836197 -0.82984457 -0.82984457]
 [ 0.55396131 -1.13349345 -0.80629856 -0.10361875  1.71566036  1.71566036]
 [ 0.38346511  0.50924869 -0.59924518 -0.34770765  0.05773649  0.05773649]]
Rank of the matrix B is 4
[[-0.13405907  1.22997352  0.23956173  0.82741005 -1.1007462  -1.7705159 ]
 [-0.87263553 -1.8660644   0.61202205 -0.86053109 -0.5077579   1.14427788]
 [-0.86483823 -0.97610645  0.24360153 -0.91011089 -0.52505705 -0.02842761]
 [-0.86483823 -0.97610645  0.24360153 -0.91011089 -0.52505705 -0.02842761]]
Rank of the matrix C is 3
[[ -2.  -2.  -2.  15.]
 [  8.   8. -23.  -3.]
 [-10. -10. -10.  -6.]
 [-15. -15. -16.  -9.]]
[[ -2.  -2.  -2.  15.]
 [  8.   8. -23.  -3.]
 [-10. -10. -10.  -6.]
 [-15. -15. -16.  -9.]]
Rank of the matrix A is 3
Rank of the matrix B is 3


Code challenge, create reduced matrix with matrix multiplication



In [5]:
M = 10
N = 10
r = 4

A = np.random.randn(M,r)
Br = np.random.randn(r,N)

C = A@Br

rank = np.linalg.matrix_rank(C)
print("rank is " + str(rank))
print(C)

rank is 4
[[ 2.7773203  -0.0256985  -0.14491908  0.13395783 -0.83551626  1.48949474
  -0.03434225  3.11513661 -0.27737108 -0.51627308]
 [ 1.38760352 -0.33073532  0.48182534 -0.32300163 -4.26307031  3.39552171
  -0.6884008   3.04614366 -1.05560234  0.50885397]
 [ 0.49636303 -0.34416064  0.04493755 -0.02884051  4.51303509 -2.51612154
   0.27955661 -2.02297748  0.37864594 -0.43012524]
 [ 1.98351368 -0.77921202  0.60572105 -0.34265399  3.08550554 -0.91005593
  -0.27729136 -0.35068672 -0.52699133  0.01974993]
 [-1.14201627 -0.78773723  0.26791664 -0.5671631  -3.38017475  2.63916023
  -0.32448354 -0.29250574 -0.10305045 -0.061078  ]
 [-1.00781196 -0.1809194  -0.49758354  0.02163179  0.69016876 -0.33416926
   0.4992391  -1.45726678  0.96833916 -0.93923933]
 [-1.33843524  0.46597948 -0.72941869  0.29425856 -1.89554942  0.70533861
   0.46334287  0.11502383  0.83504645 -0.6213008 ]
 [-2.82366085  0.87656765 -0.80346663  0.39966948 -3.11525818  0.6655303
   0.45470476 -0.34782936  0.87724985 -0.1

scalar multiplication invariant to scalar multiplication
Question is of rank(A) is equal or not equal to rank(l*A)

In [9]:
#Full rank and reduced rank matrix
M = 10
N = 10
r = 4

F = np.random.randn(M,M)
R = np.random.randn(M,r)@np.random.randn(r,N)

l = 7

rankF = np.linalg.matrix_rank(F)
rankLF = np.linalg.matrix_rank(l*F)
rankR = np.linalg.matrix_rank(R)
rankLR = np.linalg.matrix_rank(l*R)
print("rank of F:" + str(rankF))
print("rank of R:" + str(rankR))
print("rank of l*F:" + str(rankLF))
print("rank of l*R:" + str(rankLR))

lrankF = l*np.linalg.matrix_rank(F)
print("l*rank of F:" + str(lrankF))

rank of F:10
rank of R:4
rank of l*F:10
rank of l*R:4
l*rank of F:70


rank of AtA and AAt

In [4]:
m = 14
n = 3

A = np.random.randn(m,n)

AtA = np.transpose(A)@A
AAt = A@np.transpose(A)

Ar = np.linalg.matrix_rank(A)
AtAr = np.linalg.matrix_rank(AtA)
AAtr = np.linalg.matrix_rank(AAt)

Code challenge

In [6]:
n = 2
m = 5

A = np.random.randn(n,m)
B = np.random.randn(n,m)

AtA = np.transpose(A)@A
BtB = np.transpose(B)@B

Ar = np.linalg.matrix_rank(A)
Br = np.linalg.matrix_rank(B)
AtAr = np.linalg.matrix_rank(AtA)
BtBr = np.linalg.matrix_rank(BtB)

AandB = AtA + BtB
AB = AtA@BtB

AandBr = np.linalg.matrix_rank(AandB) #expect 4
ABr = np.linalg.matrix_rank(AB) # expect 2

adding l * I increase the rank of a matrix

In [4]:
import matplotlib.pyplot as plt

n = 2
m = 5
l = 0.01

A = np.round(10*np.random.randn(n,m))
AtA = np.transpose(A)@A

#A increased rank
Air = AtA + l* np.identity(m)

print("rank of AtT is " + str(np.linalg.matrix_rank(AtA)))
print("rank of Air is " + str(np.linalg.matrix_rank(Air)))

fig2, ax2 = plt.subplots()
im2 = ax2.imshow(np.imag(AtA),  extent=[-10,10,-10,10])
plt.show()


rank of AtT is 2
rank of Air is 5


<Figure size 640x480 with 1 Axes>


test if a vector v is in a span of another vector or matrix

In [3]:
v = np.array([[1,2,3,4]])

S = np.array([[4,3,6,2],[0,4,0,1]])
T = np.array([[1,2,2,2],[0,0,1,2]])

print("rank of S is " + str(np.linalg.matrix_rank(S)))
print("rank of T is " + str(np.linalg.matrix_rank(T)))

SV = np.append(S, v, axis=0)
print("rank of SV is " + str(np.linalg.matrix_rank(SV)))


TV = np.append(T, v, axis=0)
print("rank of TV is " + str(np.linalg.matrix_rank(TV)))

rank of S is 2
rank of T is 2
rank of SV is 3
rank of TV is 2
