In [2]:
import numpy as np

# Lists vs Arrays

## Adding elements to a list/array

The **+** sign in lists does concatenation, in arrays it does addition


In [10]:
# define a list
L = [1,2,3]

#define an array
A = np.array([1,2,3])

print(L)
print(A)

# loop through a list
print("\nelements of a list:")
for e in L:
    print(e)
    
# loop through an array
print("\nelements of an array:")
for e in A:
    print(e)

# append element to a list
L.append(4)
print("\nprint list after append:")
print(L)

# append element to a numpy array doesnt exists
# A.append(4)

# other way to append elements to a list
L = L + [5]
print("\nprint list after append:")
print(L)

# this type of apppend also doesn't work for arrays
# A = A + [4]

[1, 2, 3]
[1 2 3]

elements of a list:
1
2
3

elements of an array:
1
2
3

print list after append:
[1, 2, 3, 4]

print list after append:
[1, 2, 3, 4, 5]


## Vector addition

In [20]:
# in a list, every element needs to be added individual
# e.g. multiply L by 2:
L2 = []
for e in L:
    L2.append(e+e)
print("\nlist addition:")
print(L2)

# for an array
print("\nVector addition:")
A2 = A+A
print(A2)

#another way to add an array with itself is to multiply it by 2
print("\nVector multiplication:")
A2 = 2*A
print(A2)

# if we do multiplication on a list, it repeats itself
L2 = 2*L
print("\nList multiplication")
print(L2)

## element squaring doesn't work for a list, but it works for a numpy array
AA = A**2
print("\nArray squared")
print(AA)

## square root
Asqrt = np.sqrt(A)
print("\nArray square root")
print(Asqrt)

## square root
Alog = np.log(A)
print("\nArray logarithm")
print(Alog)

## square root
Aexp = np.exp(A)
print("\nArray exponential")
print(Aexp)


list addition:
[2, 4, 6, 8, 10]

Vector addition:
[2 4 6]

Vector multiplication:
[2 4 6]

List multiplication
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

Array squared
[1 4 9]

Array square root
[1.         1.41421356 1.73205081]

Array logarithm
[0.         0.69314718 1.09861229]

Array exponential
[ 2.71828183  7.3890561  20.08553692]


# The dot product 1: For loop Vs Cosine method Vs dot product


In [32]:
# create two vectors
a = np.array([1,2])
b = np.array([2,1])

# manual
dot = 0
for e,f in zip(a,b):
    dot += e*f
    
print("the doc product is " + str(dot))    

# in arrays, do element wise multiplication
m = a*b
print(m)

dot = np.sum(a*b)
print(dot)

# we can also use
dot = (a*b).sum()
print(dot)

# more convenient, numpy comes with the dot function
dot = np.dot(a,b)
print(dot)

# the dot is also a function on the array itself, so we can also use
dot = a.dot(b)
print(dot)

#magnetude is the sqrt of the sum of each element squarred
amag = np.sqrt((a*a).sum())
print("Magnetude is " + str(amag))

# Fortunately, numpy has a function for this
amag = np.linalg.norm(a)
print("Magnetude is " + str(amag))

# calculate the angle
cosangle = a.dot(b)/(np.linalg.norm(b)*np.linalg.norm(b))
print("cosangle is " + str(cosangle))

angle = np.arccos(cosangle)
print("angle is " + str(angle) + "rad")

the doc product is 4
[2 2]
4
4
4
4
Magnetude is 2.23606797749979
Magnetude is 2.23606797749979
cosangle is 0.7999999999999998
angle is 0.6435011087932847


# Vectors and Matrices

In [39]:
#a matrix
M = np.array([[1,2],[3,4]])

#a list of lists
L = [[1,2],[3,4]]

# get the first element on the first row of the list
print("first element of the first row of L: " + str(L[0][0]))

#the same can be done on the matrix
print("first element of the first row of M: " + str(M[0][0]))

# a short notation can be used on the matrix
print("first element of the first row of M: " + str(M[0,0]))

# there is a real matrix datatype
M2 = np.matrix([[1,2],[3,4]])
print(M2)

# but it's discouraged to use it, instead, convert it to an array
M2a = np.array(M2)
print(M2a)

#transpose an array
print(M.T)

first element of the first row of L: 1
first element of the first row of M: 1
first element of the first row of M: 1
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# Generating arrays of data

In [49]:
# create array of all zeros
Z = np.zeros(10)
print(Z)


# create a 10x10 matrix of all zeros
Z = np.zeros((10,10))
print(Z)

# create array of all ones
O = np.ones((10,10))
print(O)

# create a random array 
#uniformly distributed
R = np.random.random((10,10))
print(R)

#Gaussian distributed
G = np.random.randn(10,10)
print(G)

#calcuate the mean
print("Mean: " + str(G.mean()))

#calculate the variance
print("Variance: " + str(G.var()))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.28408461 0.08809484 0.89940207 0.51363654 0.82367274 0.99480395
  0.71325761 0.17970302 0.67034374 0.82659674]
 [0.41951977 0.73626055 0.38849934 0.64378739 0.23216691 0.52382496
  0.47991489 0.17715615 0.69903022 0.83225055]
 [0.19568381 0.69328127 0.96171359 0.51042263 0.04019819 0.41192132
  0.7842

# Matrix products

In [52]:
A = np.random.randn(5,5)
Am = A@A
Ah = A*A
print(Am)
print(Ah)

[[-0.5097427   0.22042246  2.56715309  0.93660037 -2.08417311]
 [ 0.36582433  0.11118341 -0.69011876 -0.35324208 -2.28432469]
 [-0.31367661  1.38873132 -2.08990341  0.15548427 -0.9287071 ]
 [-1.92580561  2.24986009 -1.48512738 -1.47600719  5.20349316]
 [-1.16366491 -0.76955045 -0.30469542 -0.18405673  1.55160048]]
[[2.72972859e-03 1.10663567e+00 6.56150654e-02 1.38038259e+00
  1.12697522e+00]
 [3.60572160e-01 3.65862040e-01 1.90067334e+00 1.27927832e-01
  2.81882235e+00]
 [3.72666061e-03 2.23809219e+00 6.71854013e-01 1.43029851e-02
  3.35455769e+00]
 [5.45821802e-01 1.79793074e+00 6.88251095e-01 6.84373610e-01
  2.93240764e+00]
 [6.02173332e-02 9.72539707e-01 1.01811828e-01 1.73636691e-01
  1.45435700e+00]]


# Nore matrix operations